version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "12345:12345"
    container_name: chat_server

  client1:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    container_name: chat_client1
    stdin_open: true
    tty: true

  client2:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    container_name: chat_client2
    stdin_open: true
    tty: true

  client3:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    container_name: chat_client3
    stdin_open: true
    tty: true